name: PHP CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Install dependencies (if any)
        run: |
          if [ -f "composer.json" ]; then
            composer install --no-interaction --prefer-dist
          fi

      - name: Run tests (if you have them)
        run: |
          if [ -f "phpunit.xml" ]; then
            vendor/bin/phpunit --testdox
          fi

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.D7_FTP_SERVER }}
          username: ${{ secrets.D7_FTP_USER }}
          password: ${{ secrets.D7_FTP_PASSWORD }}
          protocol: ftp          # or 'ftps' / 'sftp' depending on host
          local-dir: ./          # directory in your repo to upload
          server-dir: /home/d7tech/barole.3d7tech.com/barole/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/vendor/**
            composer.lock


